finance_tracker/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'finance_tracker'

urlpatterns = [
    # ex: /polls/
    path("", views.index_view, name="index"),
    path("dashboard/", views.dashboard_view, name= "dashboard"),
    path("accounts/", views.accounts_view, name= "accounts"),
    path("cashflow/", views.cashflow_view, name= "cashflow"),
    path("categories/", views.categories_view, name= "categories"),
    path("investments/", views.investments_view, name= "investments"),
    path("recurring/", views.recurring_view, name= "recurring"),
    path("transactions/", views.transactions_view, name= "transactions"),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('finance_tracker/',include('finance_tracker.urls')),
    path('users/',include('users.urls')),
    path('__debug__/',include('debug_toolbar.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    # ex: /polls/
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
]

finance_tracker/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.contrib.auth import get_user_model

User = get_user_model()

class Category(models.Model):
    # Decided to go with one category model for consistency in models
    class Meta:
        unique_together = ("user", "name")

    ACCOUNT = "Account"
    INCOME = "Income"
    EXPENSE = "Expense"
    INVESTMENT = "Investment"

    CATEGORY_TYPE_CHOICES = [
        (INCOME, "Income"),
        (EXPENSE, "Expense"),
        (INVESTMENT, "Investment"),
        (ACCOUNT, "Account"),
    ]
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name="categories",null=True,blank=True,)
    name = models.CharField(max_length=50,unique=True)
    category_type = models.CharField(max_length=15,choices=CATEGORY_TYPE_CHOICES)
    
    def __str__(self):
        # Display the category name and type (optional)
        return f"{self.name} ({self.category_type})"

class Account(models.Model):

    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name="accounts")
    category = models.ForeignKey(Category,on_delete=models.CASCADE,related_name="accounts",limit_choices_to={"category_type":"Account"},)
    balance = models.DecimalField(max_digits=10,decimal_places=2,validators=[MinValueValidator(0)]) 
    account_name = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.account_name} - ({self.balance})"
    
    def add_income(self, amount): # Method that adds any Income to balance of the account

        self.balance += amount
        self.save() 

    def deduct_expense(self, amount): # Method that adds any Expense to balance of the account
        self.balance -= amount
        if self.balance < 0:
            raise ValueError("Balance cannot be negative.")  
        self.save()
    
    def get_balance(self): # Method that gets balance of the account

        return self.balance
    

class Expense(models.Model):

    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name="expenses")
    account = models.ForeignKey(Account, on_delete=models.CASCADE,related_name="expenses",null=True,blank=True)
    amount = models.DecimalField(decimal_places=2,max_digits=10,validators=[MinValueValidator(0)])
    category = models.ForeignKey(Category,on_delete=models.CASCADE,related_name="expenses",limit_choices_to={"category_type":"Expense"},)
    date = models.DateField("Date of Transaction")
    description = models.TextField(max_length=140,null=True,blank=True)

    def save(self, *args, **kwargs):
        # Check if this is a new expense
        is_new = self.pk is None
        if is_new:
            self.account.deduct_expense(self.amount)  # Update account balance
        else:
            # Handle updates to existing expense (optional, e.g., adjust balance if amount changes)
            old_expense = Expense.objects.get(pk=self.pk)
            if old_expense.amount != self.amount:
                self.account.balance += old_expense.amount  # Reverse old amount
                self.account.balance -= self.amount         # Deduct new amount
                self.account.save()
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        # Add back the expense amount to the account balance when deleted
        self.account.balance += self.amount
        self.account.save()
        super().delete(*args, **kwargs)


    def __str__(self):
        return f"{self.category.name} - ({self.amount})"


class Income(models.Model):
    
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name="income")
    account = models.ForeignKey(Account, on_delete=models.CASCADE,related_name="income",null=True,blank=True)
    amount = models.DecimalField(decimal_places=2,max_digits=10,validators=[MinValueValidator(0)])
    category = models.ForeignKey(Category,on_delete=models.CASCADE,related_name="income",limit_choices_to={"category_type":"Income"},)
    date = models.DateField("Transaction Date")
    description = models.TextField(blank=True,null=True)
   
    def save(self, *args, **kwargs):
        # Check if this is a new income
        is_new = self.pk is None
        if is_new:
            self.account.add_income(self.amount)  # Update account balance
        else:
            # Handle updates to existing income (optional, e.g., adjust balance if amount changes)
            old_income = Income.objects.get(pk=self.pk)
            if old_income.amount != self.amount:
                self.account.balance -= old_income.amount  # Reverse old amount
                self.account.balance += self.amount       # Add new amount
                self.account.save()
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        # Deduct the income amount from the account balance when deleted
        self.account.balance -= self.amount
        self.account.save()
        super().delete(*args, **kwargs)

    def __str__(self):
        return f"{self.category.name} - ({self.amount})"


class RecurringTransaction(models.Model):
# Define transaction type choices
 
    # Define frequency choices
    DAILY = "Daily"
    WEEKLY = "Weekly"
    BIWEEKLY = "Biweekly"
    MONTHLY = "Monthly"
    YEARLY = "Yearly"
    FREQUENCY_CHOICES = [
        (DAILY, "Daily"),
        (WEEKLY, "Weekly"),
        (BIWEEKLY, "Biweekly"),
        (MONTHLY, "Monthly"),
        (YEARLY, "Yearly"),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="recurring_transactions")
    amount = models.DecimalField(max_digits=15, decimal_places=2,validators=[MinValueValidator(0)])
    category = models.ForeignKey(Category,on_delete=models.CASCADE,related_name="recurring_transactions",limit_choices_to={"category_type__in":
    ["Income","Expense"]},)
    start_date = models.DateField()  # When the recurring transaction begins
    frequency = models.CharField(max_length=15,choices=FREQUENCY_CHOICES)
    end_date = models.DateField(null=True, blank=True)  # When it ends (optional)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.category.name} - ({self.amount})"

class Goal(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="goal")
    amount = models.DecimalField(max_digits=15, decimal_places=2,validators=[MinValueValidator(0)])
    category = models.ForeignKey(Category,on_delete=models.CASCADE,related_name="goals",limit_choices_to={"category_type__in":
    ["Income","Expense","Investment"]},)    
    start_date = models.DateField()  # When the goal begins
    end_date = models.DateField(null=True, blank=True)  # When it ends (optional)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.category.name} Goal: ${self.amount}"


class Investment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="investments")
    category = models.ForeignKey(Category,on_delete=models.CASCADE,related_name="investments",limit_choices_to={"category_type":"Investment"},)
    name = models.CharField(max_length=100)
    purchase_price = models.DecimalField(max_digits=15, decimal_places=2,validators=[MinValueValidator(0)])
    current_value = models.DecimalField(max_digits=15, decimal_places=2,null=True,blank=True)
    date_invested = models.DateField()
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.name} - ${self.current_value or 'N/A'}"
    
class Budget(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="budgets")
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="budgets"
    )
    amount = models.DecimalField(max_digits=10, decimal_places=2)  # Budget limit
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return f"{self.category.name} Budget: {self.amount} ({self.start_date} to {self.end_date})"

    def is_exceeded(self):
        # Calculate total expenses in the budgeted category
        total_expenses = Expense.objects.filter(
            user=self.user,
            category=self.category,
            date__range=(self.start_date, self.end_date),
        ).aggregate(total=models.Sum("amount"))["total"]
        total_expenses = total_expenses or 0
        return total_expenses > self.amount
    
class Notification(models.Model):
    INFO = "info"
    WARNING = "warning"
    ALERT = "alert"

    NOTIFICATION_TYPE_CHOICES = [
        (INFO, "Info"),
        (WARNING, "Warning"),
        (ALERT, "Alert"),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="notifications")
    title = models.CharField(max_length=100)
    message = models.TextField()
    notification_type = models.CharField(max_length=10, choices=NOTIFICATION_TYPE_CHOICES, default=INFO)
    is_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.title[:30]} ({self.notification_type})"
    

finance_tracker/views.py
from django.shortcuts import render
from .models import Account
from django.contrib.auth.decorators import login_required

# Create your views here.
def index_view(request):
    return render(request,"finance_tracker/index.html")

@login_required
def dashboard_view(request):
    accounts = Account.objects.all()

    return render(request,"finance_tracker/dashboard.html",{"accounts":accounts})
@login_required

def accounts_view(request):
    accounts = Account.objects.all()
    return render(request,"finance_tracker/accounts.html",{"accounts":accounts})

@login_required
def cashflow_view(request):
    login_required
    return render(request,"finance_tracker/cashflow.html")

@login_required
def categories_view(request):
    return render(request,"finance_tracker/categories.html")

@login_required
def investments_view(request):
    return render(request,"finance_tracker/investments.html")

@login_required
def transactions_view(request):
    return render(request,"finance_tracker/transactions.html")

@login_required
def recurring_view(request):
    return render(request,"finance_tracker/recurring.html")

finance_tracker/templates/finance_tracker/accounts.html
{% extends "finance_tracker/layout.html" %}

{% block title %}Accounts{% endblock title %}

{% block content %}

{% endblock content %}

finance_tracker/templates/finance_tracker/cashflow.html
{% extends "finance_tracker/layout.html" %}

{% block title %}Accounts{% endblock title %}

{% block content %}

{% endblock content %}

finance_tracker/templates/finance_tracker/categories.html
{% extends "finance_tracker/layout.html" %}

{% block title %}Accounts{% endblock title %}

{% block content %}

{% endblock content %}

finance_tracker/templates/finance_tracker/dashboard.html
{% extends "finance_tracker/layout.html" %}

{% block title %}Accounts{% endblock title %}

{% block content %}

{% endblock content %}

finance_tracker/templates/finance_tracker/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>NFAi Intelligent Financial Advice</title>

    <link rel="stylesheet" href="{% static 'finance_tracker/style.css' %}">
</head>

<body>
    <div class="landing-page">
        <div class="header">
            <div class="header-bar">
                <div class="header-logo">
                    NF<u>Ai</u>
                </div>
                <div class="links">
                    <ul>
                        <li><a class="topmenu" href="#features">Features</a></li>
                        <li><a class="topmenu" href="#reviews">Reviews</a></li>
                        <li><a class="topmenu"href={% url "users:register" %}>Sign Up</a></li>
                        <li><a class="topmenu"href={% url "users:login" %}>Sign In</a></li>

                    </ul>
                </div>
            </div>

            <div class="hero-area">
                <div class="hero-text">
                    <div class="hero-text-header">
                        NF<u>Ai</u> is the future of financial freedom.
                    </div>
                    <div class="hero-secondary-text">our AI-driven Investment Assistant seeks to transform your
                        financial
                        journey by providing a comprehensive, accessible, and personalized financial companion.
                    </div>

                </div>
                <div class="moneybot">
                    <img src="{% static 'images/moneybot.png' %}" alt="AI Robot" width="200px">
                </div>
            </div>
        </div>
    </div>
    <div id="features" class="info">
        <div class="info-header">What is NF<u>Ai</u>?</div>
        <div class="group-facts">
            <div class="facts">
                <img src="{% static 'images/stocks.svg' %}" alt="Vector of Stocks" width="150px">
                <div class="info-text">Keep Track of your Future.</div>

            </div>
            <div class="facts">
                <img src="{% static 'images/house.svg' %}" alt="Vector of a House" width="150px">
                <div class="info-text">Discover new Investments.</div>

            </div>
            <div class="facts">
                <img src="{% static 'images/money.svg' %}" alt="Vector of Money" width="150px">
                <div class="info-text">Achieve your Financial Goals</div>

            </div>
            <div class="facts">
                <img src="{% static 'images/Scale.svg' %}" alt="Vector of a Scale" width="150px">
                <div class="info-text">Leverage latest AI analytics</div>

            </div>
        </div>
    </div>
    <div id="reviews" class="quote-section">

        <div class="quote1">
            "With the help of NFAi's Portfolio Tracking, I was able to live off of my Passive Income and gain
            Financial Freedom!"
            <div class="quote-person">
                -John Anderson
            </div>

        </div>

        <div class="quote2">
            "NFAi helped me organize and balance my portfolio and even showed me new industries that have insane
            potential."
            <div class="quote-person">
                -Ryan Woolworth
            </div>

        </div>
    </div>
    <div class="footer">
        this project is spearheaded and single-handedly created by Mickael Carapiet.
    </div>
    </div>
</body>

</html>

finance_tracker/templates/finance_tracker/investments.html
{% extends "finance_tracker/layout.html" %}

{% block title %}Investments{% endblock title %}

{% block content %}

{% endblock content %}

finance_tracker/templates/finance_tracker/layout.html
<!DOCTYPE html>
{%load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        Finance Tracker
        {% endblock%}
    </title>
</head>
<body>
    <nav>
        <div class="header-logo">
            NF<u>Ai</u>
        </div>
        <div class="links">
            <ul>
                <li><a class="dashboard-nav" href={% url "finance_tracker:dashboard" %}>Dashboard</a></li>
                <li><a class="dashboard-nav" href={% url "finance_tracker:transactions" %}>Transactions</a></li>
                <li><a class="dashboard-nav" href={% url "finance_tracker:cashflow" %}>Cash flow</a></li>
                <li><a class="dashboard-nav" href={% url "finance_tracker:accounts" %}>Accounts</a></li>
                <li><a class="dashboard-nav" href={% url "finance_tracker:investments" %}>Investments</a></li>
                <li><a class="dashboard-nav" href={% url "finance_tracker:categories" %}>Categories</a></li>
                <li><a class="dashboard-nav" href={% url "finance_tracker:recurring" %}>Recurrings</a></li>
            </ul>
            <div> MY ACCOUNTS </div>
            
        </nav>
    <main>
        {%block content %}
        {%endblock%}
</body>
</html>

finance_tracker/templates/finance_tracker/recurring.html
{% extends "finance_tracker/layout.html" %}

{% block title %}Accounts{% endblock title %}

{% block content %}

{% endblock content %}

finance_tracker/templates/finance_tracker/transactions.html
{% extends "finance_tracker/layout.html" %}

{% block title %}Accounts{% endblock title %}

{% block content %}

{% endblock content %}