finance_tracker/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'finance_tracker'

urlpatterns = [
    # ex: /polls/
    path("", views.index_view, name="index"),
    path("dashboard/", views.dashboard_view, name= "dashboard"),
    path("accounts/", views.accounts_view, name= "accounts"),
    path("cashflow/", views.cashflow_view, name= "cashflow"),
    path("categories/", views.categories_view, name= "categories"),
    path("investments/", views.investments_view, name= "investments"),
    path("recurring/", views.recurring_view, name= "recurring"),
    path("transactions/", views.transactions_view, name= "transactions"),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('finance_tracker/',include('finance_tracker.urls')),
    path('users/',include('users.urls')),
    path('__debug__/',include('debug_toolbar.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    # ex: /polls/
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
    
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    date_of_birth = models.DateField(null=True)
    created_at = models.DateTimeField(auto_now_add=True) #Auto-generate creation timestamp

    def __str__(self):
        return f"{self.last_name.upper()}, {self.first_name}"

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate

# Get the custom user model
User = get_user_model()

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'date_of_birth', 'password1', 'password2']
        widgets = {
            'date_of_birth': forms.DateInput(attrs={'type': 'date'}),
        }

users/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm
from django.contrib.auth.forms import AuthenticationForm
# Create your views here.
def register_view(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('finance_tracker:dashboard')
    else:    
        form = CustomUserCreationForm() 
    return render(request,"users/register.html", {'form': form})


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm( data=request.POST)
        if form.is_valid():
            return redirect("finance_tracker:dashboard")  # Redirect to homepage
    else:
        form = AuthenticationForm()

    return render(request, "users/login.html", {"form": form})

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign In</title>
    {%load static %}
    <link rel="stylesheet" href="{% static 'users/style.css' %}">

</head>
<body>
    <div class="header">
        <div class="header-bar">
            <div class="header-logo">
                NF<u>Ai</u>
            </div>
            <div class="links">
                <ul>
                    <li><a class="topmenu"href={% url "finance_tracker:index" %}>Home</a></li>


                </ul>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="modal">
            <form class="form-with-validation" action="/users/login/" method="post">
                {% csrf_token %}

                {{ form.as_p}}
                <button>Submit</button>

            </form>
            <a class="reg-link" href="{% url 'users:register' %}">Don't have an account? Register</a>
        </div>
    </div>
    <div class="footer">
        this project is spearheaded and single-handedly created by Mickael Carapiet.
    </div>
</body>
</html>

users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign In</title>
    {%load static %}
    <link rel="stylesheet" href="{% static 'users/style.css' %}">

</head>
<body>
    <div class="header">
        <div class="header-bar">
            <div class="header-logo">
                NF<u>Ai</u>
            </div>
            <div class="links">
                <ul>
                    <li><a class="topmenu" href="">Home</a></li>


                </ul>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="modal">
            <form class="form-with-validation" action="/users/register/" method="post">
                {% csrf_token %}
                {{ form }}
                <button>Submit</button>
            </form>
        </div>
    </div>
    <div class="footer">
        this project is spearheaded and single-handedly created by Mickael Carapiet.
    </div>
</body>
</html>